version: "3.8"
services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    container_name: Mailcatcher

  dev:
    image: chialab/php-dev:7.4-apache
    volumes:
      - ./:/var/www/
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8080:80"
    container_name: Flora
    working_dir: /var/www
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  default:
    external:
      name: Flora-Network
